[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient
	adafruit/DHT sensor library
	jsnkan/lcd128_32_io@^1.0.1
